device: cuda
dataset:
  name: ImageNet
  dataset_dir: indoor_binary
  image_size: 224
  n_channels: 3
  n_classes: 1000
model:
  type: imagenet
  name: vgg
  init_mode: kaiming_fan_out
  vgg:
    n_channels: [64, 128, 256, 512, 512]
    n_layers: [2, 2, 3, 3, 3]
    use_bn: True
train:
  use_apex: True
  resume: False
  seed: 0
  precision: O0
  batch_size: 256
  subdivision: 8
  optimizer: sgd
  base_lr: 0.01
  momentum: 0.9
  nesterov: True
  weight_decay: 5e-4
  output_dir: experiments/imagenet/vgg16/exp00
  log_period: 10
  checkpoint_period: 10
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 8
    drop_last: True
    pin_memory: True
validation:
  batch_size: 256
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: True
scheduler:
  epochs: 90
  type: multistep
  milestones: [30, 60]
  lr_decay: 0.1
augmentation:
  use_random_crop: False
  use_gaussianblur: False
  use_colorjitter: False
  use_center_crop: False
  use_random_horizontal_flip: False
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
  use_random_vertical_flip: False
  use_random_perspective: False
  use_random_rotation: False
  use_randomresizecrop: False
tta:
  use_resize: True
  use_center_crop: False
  resize: (256,256)
tensorboard:
  train_images: False
  val_images: False
  model_params: False
